project_config/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularRedocView, SpectacularSwaggerView

from users.views import approval_requests

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('api/', include('scripts.urls')),
    path('approval-requests/', approval_requests, name='approval_requests'),
    # docs urls for drf-spectacular
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/schema/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    path("api/schema/swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger"),
    path("", lambda request: redirect("swagger", permanent=False)),
]

users/urls.py
from allauth.account.views import ConfirmEmailView
from django.urls import path, re_path
from dj_rest_auth.registration.views import RegisterView, VerifyEmailView
from dj_rest_auth.views import LoginView, LogoutView, PasswordResetConfirmView, PasswordResetView
from . import views

urlpatterns = [
    path('', views.UserListView.as_view()),
    path('account-confirm-email/<str:key>/', ConfirmEmailView.as_view()),
    path('register/', RegisterView.as_view(), name='register_user'),
    path('login/', LoginView.as_view(), name='user_login'),
    path('logout/', LogoutView.as_view(), name='user_logout'),
    path('verify-email/',
         VerifyEmailView.as_view(), name='rest_verify_email'),
    path('account-confirm-email/',
         VerifyEmailView.as_view(), name='account_email_verification_sent'),
    re_path(r'^account-confirm-email/(?P<key>[-:\w]+)/$',
            VerifyEmailView.as_view(), name='account_confirm_email'),
    path('password-reset/', PasswordResetView.as_view()),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    # TODO: remove after integration
    path("test_notifications/", views.TestNotifications.as_view(), name="test_notifications"),
    path("download/<int:script_id>/<str:filename>/", views.download_file, name="download_file"),
    path("download_icon/<int:command_id>/", views.download_icon, name="download_icon"),
    path("rasa/port/<int:user_id>/", views.RasaPortView.as_view(), name="get_rasa_port"),
]

scripts/models.py
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.db import models

from users.models import CustomUser


class BaseScript(models.Model):
    name = models.TextField(default='_New')
    file = models.FileField(upload_to='files/', null=True)
    dependency = models.FileField(upload_to='files/', null=True)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    type = models.CharField(default='py', max_length=100)

    def __str__(self):
        return self.file.name


class BaseCommand(models.Model):
    name = models.CharField(max_length=250)
    script = models.ForeignKey(BaseScript, on_delete=models.CASCADE)
    description = models.TextField(null=True)
    executable_url = models.URLField(null=True, max_length=1024)
    owner = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    state = models.CharField(
        max_length=100,
        choices=[
            ('public', 'Public'),
            ('private', 'Private'),
        ],
        default='private',
    )
    icon = models.ImageField(upload_to='images/', default='images/default_icon.jpg')
    used_by = models.ManyToManyField(CustomUser, related_name='used_by')

    def __str__(self):
        return self.name


class Patterns(models.Model):
    syntax = models.TextField()
    command = models.ForeignKey(BaseCommand, on_delete=models.CASCADE)


class Parameters(models.Model):
    order = models.IntegerField()
    name = models.CharField(max_length=250)
    type = models.CharField(max_length=250)
    command = models.ForeignKey(BaseCommand, on_delete=models.CASCADE)


class CommandApproveRequest(models.Model):
    """
    This model is used to store the requests for approving a command.
    when a user set the visibility of a command to public, the command is saved as private,
    and a request is created for the admin to approve the command to be public.
    when the admin approve the command, the command is set to public.
    if the admin reject the command, the command is set to private.
    if the status was updated to pending again, the command is set to private.
    """
    command = models.ForeignKey(BaseCommand, on_delete=models.CASCADE)
    status = models.CharField(
        max_length=100,
        choices=[
            ('pending', 'Pending'),
            ('approved', 'Approved'),
            ('rejected', 'Rejected'),
        ],
        default='pending',
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if self.status == 'approved':
            self.command.state = 'public'
            self.command.save()

            channel_layer = get_channel_layer()
            async_to_sync(channel_layer.group_send)(
                f'notification_{self.command.owner.id}',
                {'type': 'send_notification',
                 'message': {
                     "type": "approved",
                     "id": self.command.id,
                     "name": "",
                     "message": "",
                     "status": ""}
                 }
            )
        else:
            self.command.state = 'private'
            self.command.save()

        super().save(*args, **kwargs)

users/models.py
import requests
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    name = models.CharField(blank=True, max_length=255)
    port = models.IntegerField(blank=True, null=True)

    def save(self, *args, **kwargs):
        last_user = CustomUser.objects.last()
        if last_user:
            if last_user.port:
                self.port = last_user.port + 1
            else:
                self.port = 8100
        else:
            self.port = 8100

        # send to nlp manger to create the user
        requests.post('http://localhost:8002/user/', json={
            'user_id': self.id,
        })

        super().save(*args, **kwargs)

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('username', 'email')


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = UserChangeForm.Meta.fields

users/views.py
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.contrib.admin.views.decorators import staff_member_required
from django.http import HttpResponse, FileResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View
from rest_framework import generics
from rest_framework.permissions import AllowAny

from scripts.models import CommandApproveRequest, BaseScript, BaseCommand
from . import models
from . import serializers


class UserListView(generics.ListAPIView):
    queryset = models.CustomUser.objects.all()
    serializer_class = serializers.UserSerializer


def download_file(request, script_id, filename):
    script = get_object_or_404(BaseScript, id=script_id)
    file = getattr(script, filename)
    response = FileResponse(file)
    response['Content-Disposition'] = f'attachment; filename="{file.name}"'
    return response


def download_icon(request, command_id):
    command = get_object_or_404(BaseCommand, id=command_id)
    file = command.icon
    response = FileResponse(file)
    response['Content-Disposition'] = f'attachment; filename="{file.name}"'
    return response


@staff_member_required
def approval_requests(request):
    requests = CommandApproveRequest.objects.filter(status='pending')

    if request.method == 'POST':
        request_id = request.POST.get('request_id')
        new_status = request.POST.get('new_status')

        approval_request = get_object_or_404(CommandApproveRequest, id=request_id)
        approval_request.status = new_status
        approval_request.save()

        return redirect('approval_requests')

    return render(request, 'approval_requests.html', {'requests': requests})


# TODO: remove after integration
class TestNotifications(generics.GenericAPIView):
    permission_classes = [AllowAny]

    def get(self, request, *args, **kwargs):
        self.create_notification(17, "This is a test notification")
        return HttpResponse("Notification sent")

    def create_notification(self, user_id, message):
        notification_data = {
            "id": 2,
            "name": "command_name",
            'status': 'success',
            'message': 'Command for the script "{script.name}" has been built successfully',
            'executable_url': "https://storage.googleapis.com/executables-ma/dist%5Copen-chrom.exe"
        }
        print(f"Sending notification to user {user_id}")
        channel_layer = get_channel_layer()
        async_to_sync(channel_layer.group_send)(
            f'notification_rasa_{user_id}',
            {
                'type': 'send_rasa_notification',
                'message': notification_data
            }
        )


class RasaPortView(View):
    def get(self, request, user_id):
        user = get_object_or_404(models.CustomUser, id=user_id)
        return HttpResponse(status=200,
                            content=f'{{"port": {user.port}}}',
                            content_type='application/json')

users/templates/approval_requests.html
<!DOCTYPE html>
<html>
<head>
    <title>Approval Requests</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            padding: 20px;
        }

        h1 {
            text-align: center;
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            background-color: #fff;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }

        th, td {
            padding: 10px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }

        td {
            border-bottom: 1px solid #ddd;
        }

        td a {
            color: #337ab7;
            text-decoration: none;
        }

        td a:hover {
            text-decoration: underline;
        }

        form {
            display: inline-block;
        }

        select {
            padding: 5px;
        }

        button[type="submit"] {
            padding: 5px 10px;
            background-color: #4CAF50;
            color: white;
            border: none;
            cursor: pointer;
        }

        button[type="submit"]:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
<h1>Approval Requests</h1>

<table>
    <tr>
        <th>Command</th>
        <th>Parameters</th>
        <th>Script</th>
        <th>Dependency</th>
        <th>Update Status</th>
    </tr>
    {% for request in requests %}
        <tr>
            <td>{{ request.command.name }}</td>
            <td>
                {% for parameter in request.command.parameters_set.all %}
                    {{ parameter.name }} ({{ parameter.type }})<br>
                {% endfor %}
            </td>

            <td><a href="{% url 'download_file' script_id=request.command.script.id filename='file' %}">Download Script</a></td>
            <td><a href="{% url 'download_file' script_id=request.command.script.id filename='dependency' %}">Download Dependency</a></td>
            <td>
                <form method="POST" action="{% url 'approval_requests' %}">
                    {% csrf_token %}
                    <input type="hidden" name="request_id" value="{{ request.id }}">
                    <select name="new_status">
                        <option value="pending" {% if request.status == 'pending' %}selected{% endif %}>Pending</option>
                        <option value="approved" {% if request.status == 'approved' %}selected{% endif %}>Approved
                        </option>
                        <option value="rejected" {% if request.status == 'rejected' %}selected{% endif %}>Rejected
                        </option>
                    </select>
                    <button type="submit">Update</button>
                </form>
            </td>
        </tr>
    {% endfor %}
</table>
</body>
</html>